# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Elena D'Onghia's Dynamics Group
email: edonghia@astro.wisc.edu
description: > # this means to ignore newlines until "baseurl:"
  Github page for Elena D'Onghia's dynamics group.
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  DOnghiaGroup

# Build settings
markdown: kramdown
